
--DATA PREPARATION AND UNDERSTANDING
--1.	What is the total number of rows in each of the 3 tables in the database?
select count(cust_id) as no_of_rors from Transactions
select count(customer_Id) as no_of_rows from Customer
select COUNT(prod_cat) as no_of_rows from prod_cat_info

--2.	What is the total number of transactions that have a return?
select count(cast(total_amt as float)) as no_of_transaction
from Transactions
where cast(total_amt as float)<0

--3.	As you would have noticed, the dates provided across the datasets are not in a correct format. 
--As first steps, pls convert the date variables into valid date formats before proceeding ahead.


--4.	What is the time range of the transaction data available for analysis? 
--Show the output in number of days, months and years simultaneously in different columns.

select *
from Transactions

--5.Which product category does the sub-category “DIY” belong to?
select prod_cat
from prod_cat_info
where prod_subcat='diy'

--DATA ANALYSIS
--1.Which channel is most frequently used for transactions?
select Store_type,count(Store_type) as no_of_count
from Transactions
group by Store_type
order by no_of_count desc

--2.What is the count of Male and Female customers in the database?
select gender,count(Gender) as total_count
from Customer
where gender<>' '
group by Gender

--3.From which city do we have the maximum number of customers and how many?
select top 1 city_code,count(customer_Id) as total_cust
from Customer
group by city_code
order by total_cust desc

--4.How many sub-categories are there under the Books category?
select count(prod_subcat) as total_subcat
from prod_cat_info
where prod_cat='books'

--5.What is the maximum quantity of products ever ordered?
select prod_cat,count(transaction_id) as prod_count
from Transactions as t
inner join prod_cat_info as p
on t.prod_cat_code=p.prod_cat_code
and t.prod_subcat_code=p.prod_sub_cat_code
group by prod_cat
order by prod_cat

--6.What is the net total revenue generated in categories Electronics and Books?

select p.prod_cat,
round(sum(cast(total_amt as float)),2)as Net_revenue
from Transactions as t 
inner join prod_cat_info as p                 --doubt
on t.prod_cat_code=p.prod_cat_code
and t.prod_subcat_code=p.prod_sub_cat_code
where prod_cat in ('electronics','books')
group by p.prod_cat

--7. How many customers have >10 transactions with us, excluding returns?
select cust_id,count(cust_id)as cust_count     --doubt
from Transactions
where cast(total_amt as float)>0
group by cust_id
having count(cust_id)>10

--8. What is the combined revenue earned from the “Electronics” & “Clothing”
--categories, from “Flagship stores”?

     select sum(cast(total_amt as float)) as revenue
     from Transactions as t 
     inner join prod_cat_info as p                           --doubt
     on t.prod_cat_code=p.prod_cat_code
     and t.prod_subcat_code=p.prod_sub_cat_code
     where prod_cat in ('electronics','clothing')
	 and Store_type ='flagship stores' 
	 select * from Transactions
--9. What is the total revenue generated from “Male” customers in “Electronics”
--category? Output should display total revenue by prod sub-cat.
select prod_subcat,sum(cast(total_amt as float)) as revenue
from Customer as c
inner join Transactions as t
on customer_Id=cust_id
inner join prod_cat_info as p
on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where prod_cat= 'electronics' and Gender='m'
group by prod_subcat


--10.	What is percentage of sales and returns by product sub category;
--display only top 5 sub categories in terms of sales?
select top 5 prod_subcat,sales/(select sum(cast(total_amt as float)) from Transactions where cast(total_amt as float)>0)* 100 
as [%sales],return_sales/(select abs(sum(cast(total_amt as float))) from Transactions where cast(total_amt as float)<0)* 100 as [%returnsale]
from(
       select prod_subcat,sum(s) as sales  , sum(rs) as return_sales
       from(
                select prod_subcat,
                Case
                    when cast(total_amt as float)>0
                	then cast(total_amt as float)
                	else 0
                	end as s,
                case    
                    when cast(total_amt as float)<0
                	then abs(cast(total_amt as float))
                	else 0
                	end as rs
                
                from Transactions as t
                inner join prod_cat_info as p
                on t.prod_cat_code=p.prod_cat_code
                and t.prod_subcat_code =p.prod_sub_cat_code
        ) as x
        group by prod_subcat
) as y
order by  sales desc



--11.	For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in 
--last 30 days of transactions from max transaction date available in the data?
select x.customer_Id ,sum(cast(x.total_amt as float)) as total_revenue
from(
		select *
		from Customer as C
		inner join Transactions as T
		On C.customer_Id = T.cust_id
		where datediff(day,cast(tran_date as date),(select Cast(Max(tran_date) as date)from transactions)) <= 30
		) as x
where datediff(year,cast(DOB as date),cast(GETDATE() as date)) between 25 and 35
group by x.customer_Id 
 





--12.	Which product category has seen the max value of returns in the last 3 months
--of transactions?
 select top 1 p.prod_cat,
 case 
 when cast(total_amt as float)>0 
 then 0
 else cast(total_amt as float)
 end as return_sale
 from prod_cat_info as p
 inner join Transactions as t
  on p.prod_cat_code=t.prod_cat_code
  and p.prod_sub_cat_code=t.prod_subcat_code
  order by return_sale asc
  -- doubt_how to solve for last 3 months

--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?
select y.store_type from 
(select top 1 Store_type, SUM(cast(Qty as int)) as QuantitySold
from Transactions
where qty > 0
group by Store_type
order by SUM(cast(Qty as int)) desc) as X
inner join
(select top 1 Store_type, round(SUM(cast(total_amt as float)),4) as SalesAmount
from Transactions
where qty > 0
group by Store_type
order by SUM(cast(total_amt as float)) desc) as Y
ON X.Store_type = Y.Store_type

--14.What are the categories for which average revenue is above the overall average.
select x.prod_cat
from (
	  select p.prod_cat ,sum(cast(t.total_amt as float)) as Revenue
	  from Transactions as T
	  inner join prod_cat_info as P
	  on t.prod_subcat_code = p.prod_sub_cat_code 
	  and t.prod_cat_code = p.prod_cat_code
	  group by p.prod_cat
) as x
where x.Revenue > 
		(
		  select avg(Revenue) 
		  from (
			  select p.prod_cat ,sum(cast(t.total_amt as float)) as Revenue
			  from Transactions as T
			  inner join prod_cat_info as P
			  on t.prod_subcat_code = p.prod_sub_cat_code 
			  and t.prod_cat_code = p.prod_cat_code
			  group by p.prod_cat
			) as Z
		)


--15.Find the average and total revenue by each subcategory for the categories which
--are among top 5 categories in terms of quantity sold

select x.prod_subcat + ': ' + x.prod_cat as Sub_category, revenue, average from 
(
	select p.prod_cat, p.prod_subcat, sum(CAST(t.total_amt as float)) as revenue,
	round(avg(CAST(t.total_amt as float)),4,2) as average
	from transactions as T
	inner join prod_cat_info as P
	on t.prod_subcat_code = p.prod_sub_cat_code 
	and t.prod_cat_code = p.prod_cat_code
	where qty>0
	group by p.prod_cat , p.prod_subcat
	) as X
	where x.prod_cat in (select top 5 p.prod_cat
						from transactions as T
						inner join prod_cat_info as P
						on t.prod_subcat_code = p.prod_sub_cat_code 
						and t.prod_cat_code = p.prod_cat_code
						where qty>0
						group by p.prod_cat
						order by count(Qty) desc)